### ISSUE TITLE
Use the post location editor on a front end form

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cyberhobo/wordpress-geo-mashup#350]
```
Is there any documentation about frontending insert of markers?
I already have a front end post system... is that any funcion that return 
last mouse click coordinates?

```

Original issue reported on code.google.com by `thiago....@gmail.com` on 25 Apr 2010 at 5:55

**Comment by nanousheka** [comment]
Hello everybody,

I need help. Need to add frontend location and map form in woocommerce/wc vendors post editor (product editor). But don't know what function or into what file and where to add in the file. I tried to understand all comments but all I can do is copy code and past where someone tell me so.

Can someone help me?
