### ISSUE TITLE
Info window showing full sized image

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cyberhobo/wordpress-geo-mashup#592]
```
Hello,

I have a problem I've been trying to figure out but can't seem to figure out. 
All of my info windows display the full-size post image in them instead of the 
post thumbnail, even though I clearly see in the info-window.php the post 
thumbnail is referenced.

Any idea why this might be happening?

Thanks in advance.
```

Original issue reported on code.google.com by `scottbje...@gmail.com` on 8 Aug 2012 at 10:45

**Comment by smadds** [comment]
I know this is an old issue, but just had the same problem with Sydney theme - a very popular one. Could you explicitly set thumbnail in the code, @GoogleCodeExporter?

btw, in the meantime the parameter needs inverted commas if you are tweaking the template:

`<?php the_post_thumbnail('thumbnail'); ?>`
