### ISSUE TITLE
Make "Geocode Custom Fields" work for users

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cyberhobo/wordpress-geo-mashup#679]
```
Geo Mashup 1.7.2

It seems like it might be pretty easy to make this functionality work for user 
meta as well, like geo_latitude and geo_longitude do. 
```

Original issue reported on code.google.com by `dylankk...@gmail.com` on 8 Nov 2013 at 1:06

**Comment by airsidworld** [comment]
Hello,
I'm a dummy in coding but i really need to get user location from a buddypress field profile.
Can you please explain me step by step how to do it. Where should I copy the code you gave (copy below), in function.php ? and which name for profile field tu use ?
Thanks a lot.

<?php 

$blogusers = get_users( $args ); // for args see codex

if ($blogusers) {
  foreach ( $blogusers as $bloguser ) {
    $user_location = get_the_author_meta('geo_address', $bloguser->ID );
    $has_meta = get_post_meta(463, 'geo_mover', true);
    if ($user_location && ! $has_meta) add_post_meta( 22, 'geo_mover', $user_location);
  }
}
?>
