### ISSUE TITLE
Some locations found fine but cannot be saved

### ISSUE THREAD

**Issue by StaggerLeee** [cyberhobo/wordpress-geo-mashup#713]
Everything works perfectly except this. Dont know why, know only it is not conflict with other plugin or theme. First tought it is UTF-8 characters in adress, but no. Tried some addresses with only Latin characters.

- Germany, Austria, UK, adresses can be saved.
- Non of the adresses in say for example Croatia can be saved.
- I tried to test on adresses with only standard Latin letters, but cannot be saved.
- Search works fine and find all adressesm and put marker on right spot.
- I click save location first, update/save Post.
- Location is gone, not saved.

Finding locations works perfectly. That makes me believe it has nothing to do with Google Maps and their servers.

**Comment by StaggerLeee** [comment]
When saving locations from some EU countries info message above says "Location updated".
But when saving in say Croatia this message box is empty, no message at all. Would it be nice to say Error, or something like this.

Div "geo_mashup_ajax_message" is just empty.

**Comment by StaggerLeee** [comment]
It is not non-latin characters. Just tested. Some city with utf-8 characters save location, some not. Biggest city in country save location, all other cities not.

Have no clue where to start to troubleshoot. All of this works directly on Google Gmap website.
Database is converted to UTF-8, checked. No JS errors in console.

**Comment by StaggerLeee** [comment]
I had luck to find 2 same adresses in 2 cities in Croatia for example.
So same non-latin characters, same settings on server, diferent city.

- One works, other not. Capitol city works, second biggest city in country doesnt. it is not some small village.

Can it be something how Geo Mashup handle provinces, county, etc ? This is only difference, beside longitude and latitude.

I repeat again, Google Map website shows all adresses right,

**'AdministrativeArea','SubAdministrativeArea','Locality','LocalityName'**

**Comment by cyberhobo** [comment]
This was caused by getting longer than expected values for some fields while geocoding. Look for this fix in 1.8.5!

**Comment by StaggerLeee** [comment]
Man thanks. It ruined all use of plugin. Now there is no limit of customizing anymore.

**Comment by StaggerLeee** [comment]
Is 1.8.5 already out there or should I wait ?

**Comment by cyberhobo** [comment]
Not yet - I want to consider some other issues for 1.8.5. You can always
get a bleeding edge version at
https://github.com/cyberhobo/wordpress-geo-mashup/archive/master.zip, but
be aware that this doesn't include compressed styles and scripts and a few
other things built for releases.
