### ISSUE TITLE
Make maps responsive (or make it an option)

### ISSUE THREAD

**Issue by jeremyclarke** [cyberhobo/wordpress-geo-mashup#715]
The more I test Geo Mashup on other devices the more it seems like it just isn't designed to work on responsive sites, which is a bummer. 

What's your solution for making a map work on both desktop and mobile? The need to pick specific height/width basically makes it impossible AFAICT. 

Have you looked at this method? It seems like the answer:

http://www.labnol.org/internet/embed-responsive-google-maps/28333/

If Geo Mashup worked with that system we could have shapes instead sizes, with the shapes (x-wide, wide, square, tall, x-tall) resizing to fit their container. 

P.S. I know I created a ticket about this on Google Code, I don't know where it went but I can't find it anywhere. The old URL was  https://code.google.com/p/wordpress-geo-mashup/issues/detail?id=714

**Comment by cyberhobo** [comment]
Thanks for creating a new issue - I guess the previous one must have been been created after I started the transition to github. I think the shape idea is nice - maybe it could be supplied instead of a height and width. This would make a nice 1.9 feature, I'll label it as such. Please feel free to take a crack at it if you're so inclined!

**Comment by jeremyclarke** [comment]
Awesome! Hopefully I'll have some time soon to find the hard coded width/height values that are blocking it!

I did a presentation about Geo Mashup at WordCamp Montreal yesterday and people were really excited :)

**Comment by cyberhobo** [comment]
Nice! If that goes up on wordpress.tv we should link to it in the wiki.

**Comment by cyberhobo** [comment]
I experimented with that markup a bit but couldn't get it working on my dev setup. If you can get an example working I'd like to see it, but for now I'm going to release 1.9.0 without it.

**Comment by cyberhobo** [comment]
Ok, I've got a shape parameter such that [geo_mashup_map shape="50%"] makes a 100% width map with a 2:1 aspect ratio. I couldn't get it to work for smaller widths, but I'll release this quietly in 1.9.1 as a start.
