### ISSUE TITLE
nearby-list.php

### ISSUE THREAD

**Issue by superpowered** [cyberhobo/wordpress-geo-mashup#716]
Comment at top reads:

 * Copy this to a file named geo-mashup-nearby-posts.php in your active theme folder
 * to customize. For bonus points delete this message in the copy!
 *

Should be:

 * Copy this to a file named geo-mashup-nearby-list.php in your active theme folder
 * to customize. For bonus points delete this message in the copy!
 *

**Comment by cyberhobo** [comment]
Thanks for catching that, your correction will be in the next release.
