### ISSUE TITLE
Compatibility with WPML

### ISSUE THREAD

**Issue by vpanugaling** [cyberhobo/wordpress-geo-mashup#717]
Good day, as I installed the wpml plugin there's an error in geo-mashup-db.php 

*Fatal error: Call to undefined method SitePress::posts_join_filter() in /CodeJet/wp-content/plugins/geo-mashup/geo-mashup-db.php on line 1664*

As I can see in the code you add some configuration to make it work with wpml

**Comment by cyberhobo** [comment]
I've applied for WPML's compatibility program - hopefully they'll help me resolve this.

**Comment by senlin** [comment]
Huge +1 for that @cyberhobo 
Can you update this thread once compatible?

**Comment by cyberhobo** [comment]
Yes, I'll try to keep this updated. I got a quick response from the support
team, but haven't heard back from the developers yet.

**Comment by senlin** [comment]
Great thanks.
You might need to follow up with the devs on that, I think the queue with requests is getting longer and longer :)

**Comment by twentyfortysix** [comment]
I will be happy if this issue would be solved soon.. Just wanna let you know ;)

**Comment by cyberhobo** [comment]
I'm in contact with a WPML developer, and they have an integration instance set up. I may need help setting up test cases there, if so I'll ask here.

**Comment by janhuntjens** [comment]
Have you got any news on this? I'm holding back my WPML updates because of this. I assume it's more complicated than my first thoughts, but didn't they just rename the posts_join_filter() function?

**Comment by jj-webholism** [comment]
Was wondering if there's been any movement, or if there's an idea of timescales on this?  WPML is long overdue for being upgraded, but this will break Geo Mashup.  I'd rather stick with Geo Mashup, but if it's going to be another few months for a fix, we might need to sadly seek out an alternative. :(

Any update would be greatly appreciated.

**Comment by cyberhobo** [comment]
I have been talking with the WPML devs and they did set up an integration site, but I can't debug or experiment with code there. I'm hoping they'll give me a copy of WPML so I can work on a new integration. If so I'll give it a shot over the holidays.

If anyone more familiar with WPML wants to take a stab at a fix, I'd be happy to review pull requests. I think the relevant historical issues and fixes are these:

The original issue: https://github.com/cyberhobo/wordpress-geo-mashup/issues/607
attempted solution: https://github.com/cyberhobo/wordpress-geo-mashup/commit/bc0a5bae2f99eb5874be37325d324a06fcb48791

followup issue: https://github.com/cyberhobo/wordpress-geo-mashup/issues/627
followup commit: https://github.com/cyberhobo/wordpress-geo-mashup/commit/39294262dfcb2df4a1317b18fff400a685cb90df

**Comment by cyberhobo** [comment]
I've taken a stab at an updated integration. I can verify that it removes the error messages, but I'd like confirmation that maps remain correct on a real WPML installation if possible. You can try it by replacing your geo-mashup-db.php file (version 1.8.6) with this one: https://raw.githubusercontent.com/cyberhobo/wordpress-geo-mashup/9413a08793a9a3ff7519d970a704df8a7f18b20c/geo-mashup-db.php

**Comment by senlin** [comment]
Thanks Dylan, this seems to work very well. I am now able to add a location per language (for example an office location). Of course this is only one test case, I'm sure you want to hear from others too.

One thing I noticed is that the javascript is throwing a warning in the backend:
Google Maps API warning: SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages
util.js:32

**Comment by senlin** [comment]
I think it would be a nice idea if Global Map could work in such a way that it grabs the location of each individual language and displays them in a global map, but that probably is a bit too much to ask for :)

**Comment by cyberhobo** [comment]
Thanks Piet! This will be all I can manage for 1.8.7 I think. I did address the sensor warning in issue #732.

**Comment by senlin** [comment]
Already great that the WPML bug is finally squashed! Thanks for all your hard work!
