### ISSUE TITLE
show_on_map_link() adds 'text' argument to URL if it's used (i.e. very ugly url)

### ISSUE THREAD

**Issue by jeremyclarke** [cyberhobo/wordpress-geo-mashup#718]
One of the $args for GeoMashup::show_on_map_link() is 'text', which replaces the default text. Unfortunately when I use it the resulting link has the entire 'text' argument as a URL query arg (in addition to the proper args that are also there). 

Example:
`https://dev.gv/2015/07/01/183342/?text=Show%20on%20global%20map&center_lat=31.5546055&center_lng=74.3571548&open_object_id=183342`

It happens because the method passes the whole args array to `show_on_map_link_url()`:

`$url = self::show_on_map_link_url( $args );`

Then `show_on_map_link_url()` constructs the URL by running `add_query_arg()` on the whole $args array:

`$url = htmlentities( add_query_arg( $args, $url ) );`

There are a variety of ways to solve this and none are too complicated. The simplest would be to remove 'text' from $args before running `add_query_arg()`:

`unset($args['text']);`

Better IMHO would be to have `show_on_map_link_url()` construct it's own array with only the values that it expects as URL variables, stored in `$query_args` or something like that. This would avoid similar bugs coming up in the future, and make the method much clearer to anyone investigating.

**Comment by jeremyclarke** [comment]
FWIW I resolved this for my purposes by instead calling `GeoMashup::show_on_map_link_url()` directly and assembling the link, but that wouldn't be an option for people using the shortcode.

**Comment by cyberhobo** [comment]
Thanks Jeremy, should be fixed in the next release.
