### ISSUE TITLE
Street View Control

### ISSUE THREAD

**Issue by Sinusite** [cyberhobo/wordpress-geo-mashup#722]
hi
How to add a google street_view_control with the shortcode [geo_mashup_map] ?
Thank you !

**Comment by TWDesigns** [comment]
Looking for this as well!

**Comment by Sinusite** [comment]
Thanks ;-)

**Comment by cyberhobo** [comment]
You're welcome. It's probably worth noting here that you can set `enable_street_view="false"` to disable the peg man if needed.
