### ISSUE TITLE
Change title of Nearby List Tag

### ISSUE THREAD

**Issue by actionmatt** [cyberhobo/wordpress-geo-mashup#723]
I am using the short code for Lists Nearby and would like to change the default title (Posts Nearby) but can;t see how I do that? I am sure it is simple but there doesn't seem to be an option in the parameters for that tag?

**Comment by cyberhobo** [comment]
There isn't a parameter for title, but the template can be customized. There are some instructions at the top of the default template: https://github.com/cyberhobo/wordpress-geo-mashup/blob/master/default-templates/nearby-list.php

**Comment by actionmatt** [comment]
thanks for your reply - i have made a copy of the default template in my child theme but i cannot work out how to change the title. I realise this is my lack of knowledge and is probably very easy but could you let me know what i need to change in the geo-mashup-nearby-list.php in my theme folder to change the title?
