### ISSUE TITLE
Map not displaying correctly 

### ISSUE THREAD

**Issue by ignitebd** [cyberhobo/wordpress-geo-mashup#729]
Hi I have been using this plugin for a long while with no problems, however after the latest upgrade the map no longer appears in its placeholder, instead the site home page appears.

here is a link

http://ignitebd.co.uk/about-us/where-have-we-worked/

I am using the [geo_mashup_map] tag.

I am not sure what I have missed

Your help would be appreciated.

Regards

Paul

**Comment by cyberhobo** [comment]
Seems to be working now, must have been a temporary issue of some kind.
