### ISSUE TITLE
The geocoding request failed with status 200

### ISSUE THREAD

**Issue by airsidworld** [cyberhobo/wordpress-geo-mashup#731]
Hello,
I've created a front end user form with an "Address" custom field and filled the Geocode Custom Field field in Overall Geo Mashup Settings with "address".
It works for sometimes but then not anymore. I've to save it many times and submit the form again and again until it works again.
When it failed, in the Custom Field section of the post, it shows "geocoding_error" (instead of "geo_address" when everything is ok) as custom field name and "The geocoding request failed with status 200." as value.
Can you please help.

**Comment by airsidworld** [comment]
Anyone  ? :(

**Comment by cyberhobo** [comment]
First thing I would try is getting your own GeoNames username under Settings / Geo Mashup / Overall / Obscure settings.

Next would be to uncheck Enable Reverse Geocoding there if you're not depending on having admin or country codes for locations.

I'll leave this issue open to improve that error message - the current one doesn't give enough information about what went wrong.

**Comment by airsidworld** [comment]
Thanks a lot for your reply.
I've apply your advices and i'll let you know if the error happens again.

**Comment by airsidworld** [comment]
Just sign up to GeoNames, add my GeoNames username to GeoNames ID field and then uncheck Enable Reverse Geocoding.
Save settings, try it. Not working at all.
Delete "address" in Geocode Custom Field, save settings, rewrite "address" in Geocode Custom Field and save again. Before, after doing so it was working again but now it doesn't at all.
:(

**Comment by cyberhobo** [comment]
If you're using the Google v3 map provider, getting an API key for that is also worth trying.

**Comment by airsidworld** [comment]
More information:
In the WPUF front end form I'm using also [geo_mashup_show_on_map_link] and [geo_mashup_map] in custom fields as placeholder text that I hide those fields with css (display: none;) so user doesn't see them and shortcodes results are shown on the newly created post.
Maybe it can help ?

**Comment by airsidworld** [comment]
Just get a Google v3 API key (with no restriction for it) but nothing work.

**Comment by airsidworld** [comment]
Just uncheck Copy Geodata Meta Fields boxe and save settings = > works fine for the first submit post.
Then doesn't work anymore for others posts.
I don't understand anything.

**Comment by cyberhobo** [comment]
I've expanded the error reporting so it should be possible to identify the problem. You can try it by replacing geo-mashup/geo-mashup-geocoders.php with this version:

https://raw.githubusercontent.com/cyberhobo/wordpress-geo-mashup/cabe30a330e9b49e634944e5871986382f204137/geo-mashup-geocoders.php

**Comment by airsidworld** [comment]
Hi,
Thanks for your support again.
I've replaced the file and just submit 6 posts in a row...everything works fine for now on.
I'll let you know if error happens again.

**Comment by robhumphries** [comment]
I've been having a similar problem that has been a problem for days. 

However I think I found the source. If Search Engine Visibility is checked in Wordpress settings, then Wordpress will through the 200 Error and Geomashup is unable to process the custom field.

For good measure I also refreshed the Wordpress premlinks to update the htacess.
