### ISSUE TITLE
Extend an existing shortcode with new parameter

### ISSUE THREAD

**Issue by titaniumbones** [cyberhobo/wordpress-geo-mashup#736]
My students have asite with several maps, all of them involving an image overlay for a historical map. I'd like to conditionally load the image overlay into the map by adding a new parameter to geo_mashup_map.  I guess I would store the overlay data in a global object array, like:
[{ url: '/path/to/map', bounds:[40.2342,40.129384018,-79.3489210, -70.3298149874]}]

and then use the new parameter to grab the appropriate image and bounds for the desired overlay. I'd use that information to generate the js.  So I guess that custom.js is not the right place to do this kind of work.  

Is there somewhere I can look to see how an operation like this would be accomplished? Thank you!
m

**Comment by cyberhobo** [comment]
I don't have an example on hand, but I would do this in custom.js. You'll probably have to use a native API, probably following the [google v3 example](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Javascript-API#usage). I think undocumented shortcode parameters may make it into the properties parameter in custom actions - shouldn't be too hard to verify.
