### ISSUE TITLE
Search widget - restrict to post types

### ISSUE THREAD

**Issue by actionmatt** [cyberhobo/wordpress-geo-mashup#740]
Is it possible to restrict the Geo Mashup Search widget to only search for set post types? I have custom post-types that I want to restrict the search to, rather than a category (which seems to be the only definable option on the widget). If not could these be a feature request for the future?

**Comment by cyberhobo** [comment]
That could be implemented as a new feature. What is possible now is to [customize the search form](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Feature-Usage#templating) and add an input with the name map_post_type. To restrict to a single post type it could be as simple as `<input type="hidden" name="map_post_type" value="custom_type"/>`.

**Comment by actionmatt** [comment]
Thanks for the reply. I really want to be able to choose on a case by case basis what the search form searches for - so if that is a future possibility for the widget that would be great.
