### ISSUE TITLE
Restrict map to category

### ISSUE THREAD

**Issue by actionmatt** [cyberhobo/wordpress-geo-mashup#741]
I am trying to restrict a map to just show post-types for a set category - I note that the Query Variables have a map_cat option but I can't get it to work and must be doing something wrong. 

I am assuming you use it like: 

[geo_mashup_map map_cat="179"]

But that is not working?

**Comment by cyberhobo** [comment]
map_cat is working on my development install. Can you publish a map that demonstrates the issue?

**Comment by actionmatt** [comment]
I am using geo-mashup with different post-types and this map I am trying to just show posts using the portfolio post types from one portfolio_category category. I am using this short code - [geo_mashup_map map_cat="179"] - but as you see no map appears (should be where the white space is at top of page. If I change it to show all posts then it works fine.

Page in questions is here - http://quietgarden.org.gridhosted.co.uk/test-garden-region-page/

Do I need specify anything else in the short code? What am I missing? Thanks.

**Comment by cyberhobo** [comment]
Can you also put in a plain [geo_mashup_map] shortcode so I can see the posts that should be showing up?

**Comment by actionmatt** [comment]
Ok. I have added a plain shortcode below the other code.

**Comment by zackdn** [comment]
@actionmatt Did you ever get this resolved?

**Comment by actionmatt** [comment]
@zackdn no I didn't get it to work in the end and had to give up. still use the plugin which is great, but couldn't get this short code to work.

**Comment by togger** [comment]
I had the same problem. It works when I use it with map_content="global" 
try [geo_mashup_map_content="global" map map_cat="179"]

**Comment by anorupl** [comment]
@actionmatt 

> I am using geo-mashup with different post-types and this map I am trying to just show posts using the portfolio post types from one portfolio_category category.

> 
If you using the portfolio post type with custom taxonomy "portfolio_category". Query variable "map_cat" it will not work. Query variable map_cat="" is only for basic type taxonomy = category. For custom taxonomy like „portfolio_category” is tax_query but currently only usable with template tags (not shortcodes).

**Comment by cyberhobo** [comment]
Closing this old issue which has a reasonable explanation.
