### ISSUE TITLE
geo mashup

### ISSUE THREAD

**Issue by chiragkavathiya** [cyberhobo/wordpress-geo-mashup#742]
when two country has same zip code then its show wrong map search result 
for example zip code = 48653 -> coesfeld
but i search this zip code i get result is 48653 -> Roscommon

**Comment by cyberhobo** [comment]
See https://github.com/cyberhobo/wordpress-geo-mashup/wiki/PHP-API#geo_mashup_search_query_location_text for a way to restrict searches to a country.
