### ISSUE TITLE
Error Loading Maps

### ISSUE THREAD

**Issue by chonil** [cyberhobo/wordpress-geo-mashup#744]
Hi, the plugin gives an error on the on the embedded page using a shortcode. "This page didn't load Google Maps correctly. See the JavaScript console for technical details." 

Any idea how i could resolve this?

**Comment by macram** [comment]
I assume you actually put a valid Google API key in the settings page, right?

**Comment by cyberhobo** [comment]
I'll reopen this if you can supply an URL where the problem occurs, otherwise there is not enough information to reproduce the problem.
