### ISSUE TITLE
Error loading maps in admin form

### ISSUE THREAD

**Issue by macram** [cyberhobo/wordpress-geo-mashup#745]
When creating a new post, the form to select the geolocation returns a MissingKeyMapError error when using GoogleV3. The map first appear, then shows the error message.

Posts when geolocation added using another provider like Leaflet shows flawlessly the Google V3 map in the post page. 

Leaflet or OpenStreetMap (or whatever is it called now) works flawlessly.

In a local MAMP server it works without problem. It must be a problem with my server.

WordPress 4.5.3, GeoMashup 1.8.8.

**Comment by cyberhobo** [comment]
I was only getting the NoApiKey warning, but the commit above fixes that. Can you replace geo-mashup-ui-managers.php with this version and report back?

https://raw.githubusercontent.com/cyberhobo/wordpress-geo-mashup/2f238710614680c1f37d4981e5b625f3a43ce461/geo-mashup-ui-managers.php

**Comment by DennisOng** [comment]
I had the same issue, and that solve it for me. Was just about to submit a PR for this but didn't have the right permissions :) Good that you've got it resolved.

Thanks.

**Comment by cyberhobo** [comment]
@DennisOng you can submit a PR from your own fork with no special permissions, but if push access would encourage you don't hesitate to mention that in other issues! Thanks for the confirmation here.

**Comment by macram** [comment]
Hello,

Last commit fixes my problem.

Thank you very much!

**Comment by DennisOng** [comment]
@cyberhobo Ah I see, I wasn't aware of this method. Thanks for that, will try it next time.

**Comment by DennisOng** [comment]
Also thanks for this great plugin, saved me heaps of programming hours :)

**Comment by jeremyclarke** [comment]
Does this mean that we are required to have an API key with the new version of GM?

I'm having huge problems updating the plugin. If I leave it at the old version I was using (1.8.6) Then everything seems to work fine, but if I use the new 1.8.9 version the location editor stops being able to add location on posts. 

I watched the console for errors. On loading the add new post screen I get: 

```
"This service requires an API key.  For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key"
```

Then later I see:

```
"Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys" util.js:208:12
"Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key"
```

Then sometimes the location search works, and I don't see other errors, but sometimes hitting enter after entering a search term does nothing, and each time I try I get a new instance of the first error:

```
"This service requires an API key.  For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key"
```

Very confusing and not sure what it means, but I figure these errors are not random. Is Google changing something to require keys but not for all requests? I use GM on a LOT of linked sites and would rather not set up keys if I don't have to. 

Thanks! Apologies if this should have been it's own ticket.

**Comment by cyberhobo** [comment]
@jeremyclarke Maybe we should start a new issue since this has now been released. Here I'll just say that the behavior seems inconsistent and it may take a few tries to make it reliable. Also it does seem like Google is inching toward requiring a key, and we'd probably be wise to plan for that.
