### ISSUE TITLE
[geo_mashup_map load_kml=http://thepath/the.kml] does after plugin update no longer work

### ISSUE THREAD

**Issue by navama** [cyberhobo/wordpress-geo-mashup#747]
Hi, the tag [geo_mashup_map load_kml=http://thepath/the.kml] does after geo_mashup_update this morning no longer work. No idea what happened, we used it for month, but suddenly the tag is no longer recognized and remains as text in the post. Also is the map in the admin page no longer updated with kml tracks.  Thanks for a help or support where to look in.

**Comment by cyberhobo** [comment]
Unable to reproduce this.
