### ISSUE TITLE
Adding map to front end Buddypress edit.php and register.php and have it submit

### ISSUE THREAD

**Issue by john-ampwebdesign** [cyberhobo/wordpress-geo-mashup#748]
I tossed this question to the users at Stackoverflow but noticed I forgot to put it here too.
---------------------------------------------------------------------------------------------
I am having a problem integrating these three plugins, well actually 4 as I have buddypress xprofile also installed.

I have the site setup with S2member Pro to deal with a membership part (log ins, payments, and more) and buddypress to deal with the profiles, emails etc.

The Geo Mashup map is on the front page to display the members locations worldwide. Right now for someone to show up on the front page map (as a user), they have to register through S2Member, pay through Paypal (if required), click through the registration email they get, fill in additional profile information using Buddypress and Xprofile. So far the location is not registered by Geo Mashup. To do this, they have to go to the wordpress profile edit in the users section and manually enter their location in the Geo Mashup map.

I have tried to make each member have a post related to them where they have to add their city, state, country. But this was very clunky as it meant the new user had to do this themselves and I need to make this easy. It also meant changing it was difficult for the user as they had to get back to that post. Not user-friendly and it doesn't show on their user-profile.

I have gone through the Geo Mashup options (and noticed that the only way to show user map icons is to not show any other icons at all).

First try: The WP registration fields I added were in the option Custom "Registration/Profile Fields" - city, state and country. The SQL result -> in wp_usermeta table the meta_value is:

   

 ` a:3:{s:4:"city";s:8:"Hamilton";s:5:"state";s:7:"Ontario";s:7:"country";s:6:"Canada";}`

Which Geo Mashup ignores.

2nd try: I then went to Xprofile to add these three items. I made three fields, city, state, country and they show up in the database in the wp_bp_xprofile_data table. I tried to write an action that would take these fields and insert it into the wp_usermeta table but Geo Mashup still did not find it.

Third try: Tried the above asking for geo_latitude and geo_longitude. Didn't work.

Is there something I am missing potentially?

Another option - put the Geo Mashup map into the Xprofile registration page. I used the PHP code to display a map but the map never shows because it needs data to show. I tried a couple of the other options available also.

    `echo GeoMashup::map( "map_content=single" );`

If I could get the map to show on the profile page or the registration page, I can ask the user to place a pin where they live or enter the location manually here (and I can take the fields out from Xprofile).

So how can I get Geo Mashup to recognize the Xprofile data or how can I make the map show so the user can place a pin on their location?

Thanks for reading, I can clear things up as needed with followups.

July 8th Edit An update: I now have the editable map showing in the profile edit page (buddypress/bp-templates/bp-legacy/buddypress/members/single/profile/edit.php) and the register page by placing this code

`<?php GeoMashupUserUIManager::get_instance()->print_form(); ?>`

into the php file before the submit button. In the functions.php (in the template) I put this code that I cobbled together from about 6 forum postings here and elsewhere.

```
$ui_manager = GeoMashupUserUIManager::get_instance();
add_action( 'profile_update', array( $ui_manager, 'save_post' ) );


function gmtest_filter_geo_mashup_load_user_editor( $enabled ) {
    global $user_id;
    if ( isset( $_GET['action'] ) and 'profile' === $_GET['action'] ) {
        $enabled = true;
        $user_id = wp_get_current_user();
        geo_mashup_edit_form( 'user', 'front_map');
        //geo_mashup_edit_form( 'user', 'profile-edit-form', $ui_manager = '');
        //geo_mashup_edit_form('profile-edit-form', $user_id, $ui_manager = '' );
    }
    return $enabled;
}
add_filter( 'geo_mashup_load_user_editor', 'gmtest_filter_geo_mashup_load_user_editor' );
include_once( '/plugins/geo-mashup/edit_form.php');
/**
 * Load location editor on the template tests page
 */
function filter_geo_mashup_load_location_editor( $load_flag ) {

        return true;

}
add_filter( 'geo_mashup_load_location_editor', 'filter_geo_mashup_load_location_editor' );
```

geo-mashup-ui-frontend.php comes from: [(https://storage.googleapis.com/google-code-attachments/wordpress-geo-mashup/issue-350/comment-25/geo-mashup-ui-frontend.php)]

'profile_update' is the ID of the form on the edit.php page.

I also tried it through a shortcode but it didn't help:

   `
function front_end_map() {
    include_once( '/plugins/geo-mashup/geo-mashup-ui-frontend.php');
    //geo_mashup_edit_form( 'user', 'front_map');

}
add_shortcode('front_end_map', 'front_end_map' );
`

So I can see the map now with the ->printform. I can select a city by placing a marker, I hit submit and the page submits and updates all the registration info but not the marker location on the map. If I look into the database I see that nothing is updated. If you look at the code, I've tried a couple variations of code that are commented out. Some edits are not here. I know I am missing something...

**Comment by cyberhobo** [comment]
Adventures in integration! This may be too slow a response for your project, but in my view a GitHub issue should result in better code or documentation, so maybe we can still achieve that. 

There was a similar thread on WPQuestions a while back that might help with the user profile submission problem: http://www.wpquestions.com/question/showChronoLoggedIn/id/17093

I had never added the key geo_mashup_load_location_editor filter to the filter documentation. It's now there, with a BuddyPress user profile example: https://github.com/cyberhobo/wordpress-geo-mashup/wiki/PHP-API#geo_mashup_load_location_editor

Are there other documentation improvements that would help?
