### ISSUE TITLE
Search nearest - restrict to UK

### ISSUE THREAD

**Issue by iannich** [cyberhobo/wordpress-geo-mashup#749]
Hi Dylan,

I posted an issue a month ago in the wordpress forum but there are currently no replies:

https://wordpress.org/support/topic/search-nearest-restrict-to-uk

I have just updated to version 1.8.9 and had to make the same modification to the code.

Hope you can help.

Regards Ian.

**Comment by cyberhobo** [comment]
A feature was added in #746 that should help. That issue includes some example code.
