### ISSUE TITLE
Showing a map with places nearby a point

### ISSUE THREAD

**Issue by dapehe94** [cyberhobo/wordpress-geo-mashup#757]
Hi

I'm tryng to display a map in a single.php page with places nearby a point. This is my code, but not working, only show the place the point:

`				<?php
				
				$latlong = explode(",", get_post_meta($post->ID, 'latlong', true) );
				$lat = $latlong[0];
				$long = $latlong[1];				
				echo GeoMashup::map( 
						array(
							'marker_select_info_window' => 'true',
							'marker_select_highlight' => 'true',
							'map_content' => 'contextual',
					        'near_lat' => $lat,
					        'near_lng' => $long,
							'radius_km' => 50,
							'limit' => 6
						) );
								
				?>`

**Comment by cyberhobo** [comment]
You probably want 'global' map_content. 'contextual' will limit items to those in [the loop](https://codex.wordpress.org/The_Loop).
