### ISSUE TITLE
Hide businesses on google maps

### ISSUE THREAD

**Issue by dapehe94** [cyberhobo/wordpress-geo-mashup#758]
Hi

Is there any way to hide businesses (shops, restaurants, etc ..) on the map?

Thank you

**Comment by cyberhobo** [comment]
It looks like there's a way to [code this as a style](http://stackoverflow.com/questions/7396722/hide-local-listings-from-google-maps-api), which would have to be done via Geo Mashup's [javascript API](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Javascript-API).
