### ISSUE TITLE
Link to geo-mashup-custom plugin missing

### ISSUE THREAD

**Issue by togger** [cyberhobo/wordpress-geo-mashup#760]
The link from https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Javascript-API to the
geo-mashup-custom plugin does not work.
see: http://wordpress-geo-mashup.googlecode.com/files/geo-mashup-custom-1.0.zip

I used a version of another project. For new users this would be a problem.

Another dead link on the page is http://wiki.geo-mashup.org/guides (user wiki guides)

**Comment by cyberhobo** [comment]
Thanks for finding those! I created a github repo for the custom plugin and updated the link to point to that. The surviving how-to guides are now at https://github.com/cyberhobo/wordpress-geo-mashup/wiki/How-To-Guides.
