### ISSUE TITLE
KML layer from google maps, labels and video not showing.

### ISSUE THREAD

**Issue by Paellaman** [cyberhobo/wordpress-geo-mashup#763]
_First my compliments for this awesome plugin._
My slight problem occurs **While adding a kml layer from google maps.**
**The labels next to the marker do not render**, nor does **embedded youtube video in the info windows**.
It shows a thumbnail of the video plus a link to youtube, but it should play in the info window.
I suppose that some extra code needs to be added for these to show on the map correctly when embedded as kml layer.
I tried using the markerwithlabel.js library but no succes.
Is there a way to make these features visible? Couldnt find the info anywhere.
To see a comparison, on [http://carriacou.biz/map/](url) you can see above the embeeded kml and below the original complete content in an Iframe.

**Comment by cyberhobo** [comment]
The Google Maps API doesn't offer much ability to change how a KML displays. You can see how a particular KML file will look without Geo Mashup involved here: https://jsfiddle.net/9epu62gr/.
