### ISSUE TITLE
[geo_mashup_term_legend] pins not hiding properly

### ISSUE THREAD

**Issue by gianners** [cyberhobo/wordpress-geo-mashup#764]
Even when I have all boxes unchecked, some pins remain on the screen.  When I click a pin, the pop-up reads [object Object].  Anyone else experience this?  Could it be an incompatible plugin?

**Comment by anorupl** [comment]
Check if the option on global map "Cluster Markers Until Zoom Level" is blank for no clustering.

**Comment by gianners** [comment]
Wow that worked...  Thank you!
