### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by funkytupperware** [cyberhobo/wordpress-geo-mashup#768]
I have had Geo Mashup installed and working perfectly on my [website](http://www.tampachanging.com/map/) for sometime now.  However, just I recently noticed that my map page is blank.  I tried updating the APIs and changing the map providers, but nothing seems to make it display properly.  Does anyone have any ideas?  Thank you.

**Comment by cyberhobo** [comment]
I think the map-style.css in your theme is the issue. You can rename that file to use the default stylesheet.
