### ISSUE TITLE
Clarify cluster setting language

### ISSUE THREAD

**Issue by byronyasgur** [cyberhobo/wordpress-geo-mashup#769]
it seems to be impossible to have clustering working at zoom levels higher than 8. I presume this is not expected behaviour.

**Comment by cyberhobo** [comment]
Can you link to an example? I'm able to cluster at higher zoom levels, so there must be other unidentified factors in play.

**Comment by byronyasgur** [comment]
This turned out to be a misunderstanding on my side. However I think the text "Highest zoom level to cluster markers, or blank for no clustering." should instead read "Highest zoom level to **continue to** cluster markers ... " because I read it like it was saying "Highest zoom level to **start to** cluster markers" which I should have realised wouldn't have made proper sense but it confused me anyway so thought I'd add my 2c in case it's something you want to change.

**Comment by cyberhobo** [comment]
I think I can improve that interface in the next release. Thanks for explaining.
