### ISSUE TITLE
GeoMashup::list_located_posts_by_area() not working

### ISSUE THREAD

**Issue by cocoholo** [cyberhobo/wordpress-geo-mashup#770]
i have tested this multiple times but something is broken.  instead of just showing 'nursing home' every single page is returned.  pls help.

```
echo GeoMashup::list_located_posts_by_area( array(
     'sort' => 'label',
     'tax_query' => array(
         array(
	 'taxonomy' => 'addtype',
	 'field' => 'slug',			
         'terms' => 'nursing home',
		)
	)
       ) ); 
?>
```

In contrast, list_located_posts worked perfectly fine. 

```
echo GeoMashup::list_located_posts( array(
     'sort' => 'label',
     'tax_query' => array(
         array(
	 'taxonomy' => 'addtype',
	 'field' => 'slug',			
         'terms' => 'nursing home',
		)
	)
       ) ); 

?>
```

**Comment by cyberhobo** [comment]
Sorry, query variables only work with list_located_posts, not list_located_posts_by_area. I've corrected the documentation to reflect this. 

The _by_area version would have to be completely rewritten to support query variables.
