### ISSUE TITLE
customizing map styles

### ISSUE THREAD

**Issue by BastianA** [cyberhobo/wordpress-geo-mashup#771]
Awesome Plugin, Sir!

I am currently looking for a way, to customize the appearance of the GoogleMap.
Here and there I read about a file called custom.js, but I was not able to find where this file belongs and how to implement it in order to modify my map.

Can you give me a quick hint? 

Thank you so much!

**Comment by cyberhobo** [comment]
I'm getting close to a release that includes integration with the [Snazzy Maps](https://wordpress.org/plugins/snazzy-maps/) plugin. It's probably worth the wait, but I have updated the [javascript API docs](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Javascript-API) to include the file location.
