### ISSUE TITLE
Tabbed category index not showing on frontpage when not logged in.

### ISSUE THREAD

**Issue by Paellaman** [cyberhobo/wordpress-geo-mashup#772]
This is a small visibility issue for visitors viewing a map legend on one page.
The Tabbed category index is not visible for visitors on the frontpage of http://carriacou.biz/ , but on other pages like http://carriacou.biz/map/ it works fine.
However, when logged into the site, this tabbed category index also shows fine on the frontpage. 
Using the same sitewide template on all pages.
It is not a real problem, but I wonder what the reason could be for this behaviour.

**Comment by cyberhobo** [comment]
A logged in / logged out difference usually indicates a caching issue. You can verify this by clearing the cache and seeing the if the issue goes away. Making sure query strings are cached could help, or excluding URLs with the geo_mashup_content query parameter.
