### ISSUE TITLE
"Warning: Missing argument 2 for wpdb::prepare(), called in" 

### ISSUE THREAD

**Issue by RodRamirez** [cyberhobo/wordpress-geo-mashup#773]
Hi! I don't know when and why this error comes up.
You can see it here: http://www.hambrientos.cl/category/restaurantes/cafe

Do you know why this happened?

Thanks!

**Comment by cyberhobo** [comment]
If you've a version prior to 1.4.12, you're seeing #605. An upgrade should fix it.

**Comment by RodRamirez** [comment]
I had to downgrade it cause' the map didn't show with the new version. I'm stuck.

**Comment by cyberhobo** [comment]
If you've customized map styles (have `map-style.css` in your theme folder), you may be seeing #768. Try renaming that file before upgrading.
