### ISSUE TITLE
Incompatibility: Async Javascript

### ISSUE THREAD

**Issue by danicasati** [cyberhobo/wordpress-geo-mashup#775]
Hi.
Plugin is broken and maps doesn't render if I use this function:

// Make JavaScript Asynchronous in Wordpress
add_filter( 'script_loader_tag', function ( $tag, $handle ) {    
    if( is_admin() ) {
        return $tag;
    }
    return str_replace( ' src', ' async src', $tag );
}, 10, 2 );

**Comment by cyberhobo** [comment]
Wouldn't that break any script with dependencies, not just Geo Mashup?

**Comment by danicasati** [comment]
Yes, some minor issues with WP User Frontend plugin, JavaScript related.

**Comment by cyberhobo** [comment]
I wouldn't expect this to work. Techniques that combine scripts with respect to dependencies might allow asynchronous loading.

**Comment by danicasati** [comment]
I've checked twice: if I remove code, maps are rendered, if I save into my FUNCTIONS.PHP Geo Maps doesn't work.
Time ago I wrote you about problem deferring Javascript too. Some incompatibilities with this?

**Comment by cyberhobo** [comment]
As you agreed, the snippet you posted will potentially break any scripts with dependencies. I'd say the snippet is not compatible with WordPress script loading.
