### ISSUE TITLE
nearby_list map_cat no longer work after update

### ISSUE THREAD

**Issue by cocoholo** [cyberhobo/wordpress-geo-mashup#777]
mine looks like this:

echo GeoMashup::nearby_list( array(
     'units' => 'km',
     'radius' => '10',
     'limit' => '20',
 'map_cat' =>'853',
        ) ); 

but after the update, it seems like map_cat is discarded. it displays everything on top of the pages from this category - 853

**Comment by cyberhobo** [comment]
Thanks for reporting that, I can reproduce it. I'll fix it in 1.10.1, meanwhile this should work:

```
echo GeoMashup::nearby_list( array(
	'units' => 'km',
	'radius' => '10',
	'limit' => '20',
	'map_terms' =>'853',
	'taxonomy' => 'category',
) );
```

**Comment by cocoholo** [comment]
'taxonomy' => 'category', doesn't work to me.

btw, i use this plugin to enable categories in my Pages
https://wordpress.org/plugins/post-tags-and-categories-for-pages/

that could be the reason why 'taxonomy' didn't work? 

i'll revert to an older version for the moment.

**Comment by cyberhobo** [comment]
Did you also change `map_cat` to `map_terms`?

**Comment by cocoholo** [comment]
oh yeah, that worked...  'map_terms' =>'853',

but 'map_terms' =>'-1084, 853',  does not

same problem with list_located_posts by the way:

mine looks like this:

echo GeoMashup::list_located_posts( array(
     'sort' => 'label',
     'tax_query' => array(
         array(
	 'taxonomy' => 'addtype',
	 'field' => 'slug',			
         'terms' => 'landmark orphanage',
		)
	)
       ) );

**Comment by cyberhobo** [comment]
Multiple terms require an array, see [the examples in the WP_Query docs](https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters).

**Comment by cocoholo** [comment]
thanks
