### ISSUE TITLE
Page not loading Google Maps correctly

### ISSUE THREAD

**Issue by bradm789** [cyberhobo/wordpress-geo-mashup#779]
Hi,

In the location section on posts, it isn't loading the map properly. Does anyone know how to get this to work?

It says "Oops! Something went wrong.            This page didn't load Google Maps correctly. See the JavaScript console for technical details"

Thanks!

**Comment by cyberhobo** [comment]
It could be a problem with your API key, but I'd have to see the JavaScript console to be sure. Where can I see an example of the issue?

**Comment by bradm789** [comment]
Dylan,

Thanks for the quick reply! Here are two screen shots showing what’s going on! Is this helpful?

Thanks.

[cid:image002.png@01D285DD.2B1E7A50]

[cid:image001.png@01D285DD.06898C70]

**Comment by cyberhobo** [comment]
Those images didn't make it through. A URL where the issue is occurring would be most useful, or you could copy and paste the output from the javascript console.
