### ISSUE TITLE
Intrusive 'Upgrade' menu item

### ISSUE THREAD

**Issue by nicomollet** [cyberhobo/wordpress-geo-mashup#784]
Hello 

Your plugin is great but the new 'Upgrade' menu has no place in the Settings menu under 'Geo mashup'.
Please remove this menu item.

Thanks
Nico

**Comment by nicomollet** [comment]
Remove this menu by defining GEO_MASHUP_FREEMIUS_OPT_OUT in wp-config.php

```
define('GEO_MASHUP_FREEMIUS_OPT_OUT', true);
```

**Comment by jerclarke** [comment]
Thank you to both of you for solving this. I run GM on dozens of sites for my org and having freemius load at all is an unwanted bottleneck.

**Comment by jerclarke** [comment]
Oh, update. I figured out that right now it's absolutely required that you put this in `wp-config.php`. Adding it in `functions.php` of your theme, or in a plugin file, won't work. 

It would be better if we could automate this with plugins/themes. Either way for anyone else, please know that `wp-config.php` is a requirement.
