### ISSUE TITLE
Ajax live filter for map

### ISSUE THREAD

**Issue by opwolken** [cyberhobo/wordpress-geo-mashup#788]
Hi I was wondering if you know if it is possible to add a live filter to the map? I am clueless on how to approach this. 

I would like to filter on taxonomies after I have searched for a location, my project can be seen on dev6.opwolken.com so after you enter your location (for example "utrecht") I would like to have the option to filter on categories etc.

I this possible?

**Comment by cyberhobo** [comment]
I've actually never tried it, but maybe you could [customize the search results template](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Feature-Usage#templating) and add a [term legend tag](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Tag-Reference#term-legend). If you try this I'd love to know if it works.

**Comment by opwolken** [comment]
Yes thank you. This is what I have done now, so I have a term legend tag included on my page (important to use "for_map="search_result_map"") and it is working :)

My next assignment is to get 2 different filters in, so not only categories but also a different tag. If you know how, please let met know!

dev6.opwolken.com and search for "tilburg"

**Comment by cyberhobo** [comment]
Very nice! Try adding a second term legend tag with taxonomy="post_tag", and make sure Settings / Geo Mashup / Overall / Collect Location For / Tags is checked.
