### ISSUE TITLE
Geo Mashup Widget Search box not showing input text box.

### ISSUE THREAD

**Issue by babyroutea** [cyberhobo/wordpress-geo-mashup#790]
Hi, Firstly,thanks for such a great mapping plugin. It's been amazing for mapping out the hikes on [Baby Routes! 
](http://babyroutes.co.uk)
I noticed that the search widget text box which I display in the rh column on my website 'Find a walk near me' is no longer displaying a text input box. It merely has the search and find me buttons. 

I've tried deactivating all other plugins but no compatibility issues found so far. 

Any idea what might be causing this? I notice from the plugin wordpress forum for this plugin that someone else has also had this issue.

Thanks so much!

**Comment by anorupl** [comment]
The conflict is about style.css in the theme. Class ".clear" hides text box and radius.

style.css :
```
.clear {
    clear: both;
    display: block;
    overflow: hidden;
    visibility: hidden;
    width: 0;
    height: 0;
}
```

**Comment by babyroutea** [comment]
Thanks so much for coming back to me about this. 
I located the code but how should I adapt to correct the issue with the search box? I'm learning on my feet!
Presumably this will be a global change to the theme...not sure how it's going to change everything else!

**Comment by anorupl** [comment]
[http://zerebny.ovh/geo/geo-mashup-search-form.zip](url)
Unpack and copy file geo-mashup-search-form.php in your active theme folder "graphene".

**Comment by cyberhobo** [comment]
Thanks for chiming in Kamil. I think it could also be fixed without overriding the search form template by adding some more specific styles:

```
form.geo-mashup-search-form .clear {
    visibility: visible;
    height: initial;
    width: initial;
}
```

**Comment by babyroutea** [comment]
Thanks so much everyone. Cyberhobo - that did the trick! :-) Thanks for taking the time to get back to me.
