### ISSUE TITLE
Front end map don't load on SSL (https) connection,

### ISSUE THREAD

**Issue by luki-zz** [cyberhobo/wordpress-geo-mashup#792]
There is an issue with map not loading on https://gorydlaciebie.pl/mapa/

The error that I get via Firebug is:
Blocked loading mixed active content “http://maps.google.com/maps/api/js?sensor=false&key=..."

There is no configuration option to change connection type to secure.

**Comment by cyberhobo** [comment]
I believe this was resolved in version 1.8.3, see #703.

**Comment by luki-zz** [comment]
Unfortunately there must be an error with pushing the changes to the final plugin. 
I have the latest version of the Geo Mashup plugin and in render-map.php on line 274 there is: 
google_3_url = 'http://maps.google.com/maps/api/js?sensor=false'

I can see that in your repository this has been changed but somehow didn't go the the final plugin.

**Comment by cyberhobo** [comment]
You're getting this from wordpress.org? I don't see that in render-map.php there:

https://plugins.trac.wordpress.org/browser/geo-mashup/tags/1.10.1/render-map.php#L237

**Comment by luki-zz** [comment]
Yes, this plugin was installed and updated via plugins page on my wordpress installation. There is no reference to the plugin version, so if there is no option to updated I assume I'm using the latest version.

**Comment by cyberhobo** [comment]
What is the WordPress version?

**Comment by luki-zz** [comment]
it's 4.7.5
I've drilled down to readme.txt and can see that I'm running Geo Mushup
1.8.1
Is it possible that previous developer disabled somehow updates of this
plugin?

Łukasz Wojnar
+48 733 560 852

2017-08-03 21:56 GMT+02:00 Dylan Kuhn <notifications@github.com>:

**Comment by cyberhobo** [comment]
Something must be preventing updates. You could try downloading the current ZIP and installing that.

**Comment by luki-zz** [comment]
Yes, thank you. Thats probably what I'll do.

Łukasz Wojnar
+48 733 560 852

2017-08-03 22:02 GMT+02:00 Dylan Kuhn <notifications@github.com>:
