### ISSUE TITLE
make marker unclickable by category

### ISSUE THREAD

**Issue by raffivitis** [cyberhobo/wordpress-geo-mashup#793]
i would like to have a category of markers that show on map but can not be clicked to open a window. 
in my case i would like to have a list of locations i have performed at just to let people see where I have been without the need for additional info.

**Comment by cyberhobo** [comment]
You can turn off info windows in Settings / Geo Mashup / Global Maps / Marker Selection Behaviors, or using the [marker_select_info_window](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Tag-Reference#map-options) attribute.

**Comment by raffivitis** [comment]
that is correct, yet it doesn't enable you, as far as I have seen, to decide that a certain category will open an info window and another one won't.

**Comment by cyberhobo** [comment]
I see, that's true. A developer could use the [javascript API](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Javascript-API) to implement it.
