### ISSUE TITLE
hide posts that has a value set at the custom field "_hide"

### ISSUE THREAD

**Issue by netzgestaltung** [cyberhobo/wordpress-geo-mashup#794]
hi,
just in case someone finds it usefull i made a little snippet to show how to hide posts to not show up in the map by a custom_fields value - i post this here because i don't know where it else may be suitable

https://github.com/netzgestaltung/wordpress-snippets/blob/master/geomashup-map-filter-posts-by-custom-value.php

**Comment by cyberhobo** [comment]
Thanks, I added a wiki page for [[Snippets]].
