### ISSUE TITLE
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by explorier** [cyberhobo/wordpress-geo-mashup#795]
Just sharing this deprecation notice I got on a PHP 7 site. Thanks for the great plugin!

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; GeoMashupCustom has a deprecated constructor in /srv/bindings/1d3f7b6cca37450b9e30814dbbacef6f/code/wp-content/plugins/geo-mashup-custom/geo-mashup-custom.php on line 31`

**Comment by cyberhobo** [comment]
Thanks for the report, hopefully that's an easy fix.

**Comment by cyberhobo** [comment]
Ah, so now I see that this is the Geo Mashup Custom plugin, not Geo Mashup itself. It was meant not to require upgrades so your customizations wouldn't be deleted, which I guess worked for over a decade ;P. 

Now the easiest way forward is probably to manually replace the geo-mashup-custom.php file with this one:

https://github.com/cyberhobo/geo-mashup-custom/blob/master/geo-mashup-custom.php

Being careful of course to leave your own customization files in the plugin folder intact.

**Comment by explorier** [comment]
Aha, great. Thanks for the patch!
