### ISSUE TITLE
Problem "loading Google Maps correctly"

### ISSUE THREAD

**Issue by freem32** [cyberhobo/wordpress-geo-mashup#796]
I am trying to insert maps onto my webpage, but keep getting the message "Oops! something went wrong.  This page didn't load Google Maps correctly.  See the JavaScript console for technical details."

JavaScript console error:

Google Maps API error: RefererNotAllowedMapError https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://activecaribbeantravel.com/wp-admin/post.php?post=19&action=edit

Yes, I have obtained an API key and placed it in my webpage plug-in.

Am I waiting for Google to "authorize" my URL?  Is there anything I need to do?

Please advise / Thanks,

Mark

**Comment by cyberhobo** [comment]
It sounds like you have the HTTP Referrers restriction set in your API key management console, in which case adding https://activecaribbeantravel.com to the list of allowed referrers should fix it.

<img width="619" alt="screenshot 2017-11-15 06 54 39" src="https://user-images.githubusercontent.com/286838/32842579-47cf7232-c9d2-11e7-8692-f882a794f8d6.png">

**Comment by freem32** [comment]
D’uh…   Sorry about that / Thanks.  I must have overwritten that at some point…  Great App / Thanks again!
