### ISSUE TITLE
Geo Search: How to css

### ISSUE THREAD

**Issue by cocoholo** [cyberhobo/wordpress-geo-mashup#797]
I'd like to apply some css but how do I do that when it keeps changing? like..

geomashupsearchwidget-19-input
geomashupsearchwidget-20-input
geomashupsearchwidget-21-input
geomashupsearchwidget-22-input

Thanks.

**Comment by cyberhobo** [comment]
Element IDs are numbered by Wordpress to ensure they're unique across all widgets, but you should still be able to style all geo search widgets using classes. The default template gives the form class geo-mashup-search-form, the location textbox geo-mashup-search-input, etc. Elements without classes can be referenced by name, e.g. select[name=radius].
