### ISSUE TITLE
Cannot get Snazzy Maps to work with Geo Mashup

### ISSUE THREAD

**Issue by mtressl** [cyberhobo/wordpress-geo-mashup#798]
I tried this with the June 2017 version, and now again with the Jan 01 2018 version.
Installed Snazzy Maps, got an API key, selected a Snazzy style. But I can not see the result in my Geo Mashup maps on my Wordpress.

Any hints what I might be missing? Thanks for your help!
M.

**Comment by cyberhobo** [comment]
There isn't much more to it. Note that it's not enough to "save" a snazzy style, you also have to enable it. If you've done that and you can give me a URL with a map that should be using a snazzy style, I'll take a look.

**Comment by mtressl** [comment]
Here are two URLs which should show Snazzy. If I got it right, every map should be Snazzy, correct?

http://dev.rumstrolchen.com/map/ (bigger one)
http://dev.rumstrolchen.com/2015/11/25/gweta-maun/ (smaller one in right side bar)

Sent you a separate email with access data.

**Comment by cyberhobo** [comment]
Huh, there are no errors and the snazzy maps script is loading. It look like you have map_type="G_SATELLITE_MAP" - what if you get rid of that or change to map_type="G_NORMAL_MAP"?

**Comment by mtressl** [comment]
Thanks for your feedback!
Which map did you look at? On the bigger one I have no parameters set except background_color="FFFFFF". On the small one I have a couple parameters, but map_type="G_HYBRID_MAP" instead the mentioned map_type="G_SATELLITE_MAP". For both, when I put map_type="G_NORMAL_MAP" nothing changes.

**Comment by mtressl** [comment]
Meanwhile I have disabled any other mapping plugin, still no success.

**Comment by cyberhobo** [comment]
I still haven't been able to see anything wrong, I may have to look into the snazzy code a little deeper to see what may be going wrong.

**Comment by mtressl** [comment]
Thanks, looking forward to get your response. If I can help or provide anything, let me know!

**Comment by cyberhobo** [comment]
Still no luck. If you have any plugins that influence the loading of scripts active you could try deactivating those. Other than that I can't see any difference between your map and a working one.

**Comment by mtressl** [comment]
From your point of view, what Plugins could that be?
- caching?
- optimization/minification?
- loading external scripts?
- other mapping plugins?

Will check more in detail if I find time.

**Comment by cyberhobo** [comment]
I would look at optimization/minification plugins first, then other mapping plugins.

**Comment by mtressl** [comment]
btw, I was not able to find a interfering extension/plugin. So unfortunately no Snazzy maps for me. Not a biggie, since your Geo Mashup is working like a charm! ;-)

**Comment by cyberhobo** [comment]
It might be worth asking the Snazzy folks if they'd like to look at it - the furthest I could get was to confirm that their code is loading and running, but it's obfuscated and I couldn't tell what was going wrong. Glad Geo Mashup serves your needs at least!
