### ISSUE TITLE
capture the phrases in the search widget

### ISSUE THREAD

**Issue by cocoholo** [cyberhobo/wordpress-geo-mashup#799]
Is it possible to record the phrases typed in the 'search widget' in Google Analytics?

I did this in WordPress using %s but I don't know how to do it in geo mashup.

Thanks.

**Comment by cyberhobo** [comment]
There isn't currently a way to make the Geo Mashup search form do a GET instead of a POST like the WordPress search form.

It is possible to track POST form submissions in Google Analytics, but it is harder to set up.
