### ISSUE TITLE
Exclude posts from Nearby List

### ISSUE THREAD

**Issue by actionmatt** [cyberhobo/wordpress-geo-mashup#800]
When using the [geo_mashup_nearby_list] shortcode is it possible to exclude posts within a certain distance? I can't find any parameters in the list that would do that, but it would be great if we could. 

Alternatively, we'd like to be able to exclude certain post-types (rather than just categories) - but again that doesn't seem to be possible?

Thanks for a great plugin!

**Comment by cyberhobo** [comment]
It looks like the map_post_type parameter should work with a comma separated list of post types to include. If that does the trick let me know and I'll add it to the documentation.

**Comment by actionmatt** [comment]
Great - yes map_post_type parameter works perfectly.

The only thing I have left is to remove the distance - is that possible. I have tried using the units parameter and setting it as units=false but that doesn’t work. Is there such a setting?

**Comment by cyberhobo** [comment]
Great, I've updated the [Tag-Reference] to document that.

Your options for the distance are to hide the span via CSS or [customize the nearby-list.php template](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Feature-Usage#templating).

**Comment by actionmatt** [comment]
Thanks Dylan for your help. 

We need some help customising the nearby-list template so I have created a question using WPQuestions - https://wpquestions.com/Geo_Mashup_Customize_Nearby_List_Template/27529 

In case you able to help us solve this.

Thank you,

Matt
