### ISSUE TITLE
Add GPS data to REST API

### ISSUE THREAD

**Issue by zebroc** [cyberhobo/wordpress-geo-mashup#802]
Hi. Thanks for this great plugin first of all!

I see that you put GPS data into the RSS feed, which is awesome.

Do you think it is possible to add the data to the output of the REST API as well?

As in, here: https://www.cyberhobo.net/wp-json/wp/v2/posts/

**Comment by cyberhobo** [comment]
I like the idea, I'll take a closer look for 1.11.0.

**Comment by Birtakimseyler** [comment]
Hi,
How can I make GPS Data visible in REST API for a Custom Post Type? Currently It works only Posts and Comments. 

Thank you.

**Comment by cyberhobo** [comment]
True, it should honor the post types enabled in the settings, but does not currently.
