### ISSUE TITLE
Infobox changes.

### ISSUE THREAD

**Issue by 1K4R0S** [cyberhobo/wordpress-geo-mashup#805]
Hi to all

I would like to change the infobox to show only the title (No excerpt, no photo etc) or just the marker to change color with the latest article without an infobox. Is it possible?

**Comment by 1K4R0S** [comment]
Thank you in advance

**Comment by cyberhobo** [comment]
It's easiest to uncheck Settings / Geo Mashup / Global Maps / Marker Selection Behaviors / Open info window to turn off the info window.

Details about customizing info window content are here: https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Feature-Usage#templating
