### ISSUE TITLE
RSS Feed breaks when plugin is activated

### ISSUE THREAD

**Issue by ses0043** [cyberhobo/wordpress-geo-mashup#807]
Hi, when I activate your plugin the RSS feed breaks. When I deactivate the plugin the the RSS feed works again. I'm sorry I don't know how to give you more information than just that.

Kind regards,
Sara

**Comment by cyberhobo** [comment]
Thanks for the report. I would need at least an error message or an example of a request to your feed URL when it is isn't working to find a cause.

**Comment by cyberhobo** [comment]
Ah, now I remember - this was reported in #108. I concluded back then that the mechanism for adding an RSS namespace provides no way to tell if it's already been added, and I think that is still the case.

**Comment by nicomollet** [comment]
Well this is really a problem.
My RSS doesn't validate and it breaks RSS widgets trying to display my RSS.
I would appreciate a way to disable Geo data from my RSS...
