### ISSUE TITLE
Zoom Level Doesn't Change

### ISSUE THREAD

**Issue by 1K4R0S** [cyberhobo/wordpress-geo-mashup#808]
Hello

I'm trying to change the loading zoom level of a specific map on the page but I don't manage.

I'm using auto_zoom_max tag reference. Is it the wrong one or am i doing something wrong?

The shortcode i use is [geo_mashup_map country_code="GB" auto_zoom="7"] for the United Kingdom map, but no matter what number of zoom level I set nothing changes.

The loading zoom number in settings for global maps is set at 5.

Thank you in advance.

**Comment by 1K4R0S** [comment]
I'm sorry. What I'm using is this:

[geo_mashup_map country_code="GB" auto_zoom_max="7"]

**Comment by cyberhobo** [comment]
The part in the [Tag-Reference#map-options] about this option being used with zoom="auto" is important. Try this:

```
[geo_mashup_map country_code="GB" zoom="auto" auto_zoom_max="7"]
```

That should give you a map auto-zoomed no closer than 7.

**Comment by 1K4R0S** [comment]
This gave me a zoom of 0 for some reason. I changed it into manual zoom="7"

**Comment by cyberhobo** [comment]
It would do that if you have locations all over the world, or even one very distant outlier that would require a low zoom level to fit in.
