### ISSUE TITLE
Disable centralization on last article's pin. Instead fix map to center.

### ISSUE THREAD

**Issue by 1K4R0S** [cyberhobo/wordpress-geo-mashup#812]
Hi 

I have a global map to show my site's articles, but I don't want the map to focus on the last article's pin but instead to centralize the whole map  and show all pins.

How can I do this?

Thank you in advance.

**Comment by cyberhobo** [comment]
In Settings / Geo Mashup / Global Maps uncheck Automatic Selection and set Default Zoom Level to auto.

**Comment by 1K4R0S** [comment]
The options were as you suggested. But it still does the same thing.

Just to make it clear. I'm not talking about the infobox. I'm talking about for example the UK map that whenever I upload a new article instead of having the whole UK map centralized it puts in the center the pin of the last article.

That is what I want to change.

**Comment by cyberhobo** [comment]
I think I understood, but I'm not sure why your results are different than mine. There are [other map tag parameters](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Tag-Reference#map-options) that allow you to set a center point (center_lat & center_lng) and zoom level (zoom) if needed.

**Comment by 1K4R0S** [comment]
After your suggestion I used this 

[geo_mashup_map map_content="global" center_lat="-0.123653" center_lng="35.786815" height="750" zoom="3"]

and still no luck. It doesn't take the new data.

**Comment by cyberhobo** [comment]
That sounds like it could be a server caching issue. If your host provides a way to clear caching you might try that.
