### ISSUE TITLE
Geomashup not importing all locations

### ISSUE THREAD

**Issue by TWDesigns** [cyberhobo/wordpress-geo-mashup#813]
I have a field called mappaddress and I've told geomashup to pull from this field. It works for a few but I have a lot that it's not tried to pull the data for. I get the following message.

id: 4 (0.0000000, 0.0000000) No address info found.

What would id 4 be referring to? There is no post id:4, so I'm unclear on the message. I think this is hanging me up from processing the other posts.

**Comment by cyberhobo** [comment]
The 4 is a location ID, probably not important here. It just means that 0.0, 0.0 was saved as a location for something at some point, and no address was found for that point as you might expect. 

Reverse geocoding means looking up address information for a known latitude and longitude. It sounds like you want regular geocoding, looking up coordinates for an address. There isn't a bulk geocoding feature, but it has been discussed a bit in #597. Geo Mashup will attempt to geocode a custom field when it is first saved, which will use the Google Server Key from the settings if available and is subject to the limits of that key.

**Comment by TWDesigns** [comment]
That makes more sense! Thank you for the explanation.
