### ISSUE TITLE
Belarussian

### ISSUE THREAD

**Issue by Nezznaika** [cyberhobo/wordpress-geo-mashup#814]
Good day, 

I can translate your plugin into Belarussian via POEdit. 

Can I expect getting a backlink to my website (hrank.com)- as the one in here:
 
Spanish by Reven added in version 1.3.3

Thanks.

**Comment by cyberhobo** [comment]
Yes, as long as your translation is accurate and not done with an automated tool, I'm happy to add a link.

**Comment by Nezznaika** [comment]
Hi,
here is the translation of the plugin to Belarussian attached.
Is it possible for our link to be added to hrank.com (without my name)
Thanks, 
Natallia

[Downloads.zip](https://github.com/cyberhobo/wordpress-geo-mashup/files/2411288/Downloads.zip)

**Comment by cyberhobo** [comment]
Thanks! I'll include that in the next release.
