### ISSUE TITLE
Info window doesn't work second time when highlight is active. (with Leaflet Map)

### ISSUE THREAD

**Issue by Birtakimseyler** [cyberhobo/wordpress-geo-mashup#820]
Hello,
Maybe not so important but I think I found a little bug.

On marker selections behaviors, I make open info window and the highlights active. But it seems there's a problem with leaflet map to use this options together. When I click a marker, everything seems ok, but after close the info window, when I click the same marker second time, info window doesn't work anymore but highlights.

You can check here: http://dev.birtakimseyler.com/

Regards

**Comment by cyberhobo** [comment]
Thanks! I think we're tracking this one already in #801, please subscribe to notifications on that issue to follow progress.
