### ISSUE TITLE
Issue - Product Not Found 

### ISSUE THREAD

**Issue by samiullahkhalid4** [cyberhobo/wordpress-geo-mashup#825]
Hi Sir,
We're using your plugin but when i search products by distance and enter zipcode the map markers showing correctly and always seeing Product Not Found.
Can you please help out me .
Thanks!

**Comment by cyberhobo** [comment]
Geo Mashup doesn't use the language "Product Not Found", so the issue is probably elsewhere. If the issue can be produced on a fresh WordPress and Geo Mashup install we can reopen this.
