### ISSUE TITLE
"This page can't load Google Maps correctly. Do you own this website?" error when there's no API key

### ISSUE THREAD

**Issue by jerclarke** [cyberhobo/wordpress-geo-mashup#826]
From what I can tell, the API key is now 100% required. Without it, I get that error when loading the page and the map says "for development purposes only". 

**I think maybe the bug here is just that GM needs to make it clear in the UI that it's not at all optional to get a key.** 

It would also be good to update the main documentation to make this clear, and give some indication of what the costs will be (as Google doesn't make this clear at all, but you could probably describe it based on plugin usage, I honestly still have no idea). 

If I'm wrong about this please let me know. I would love if the plugin could work without the API key/paying Google. 

<img width="441" alt="screen shot 2018-11-15 at 18 24 13 pm" src="https://user-images.githubusercontent.com/139995/48590299-909ab880-e904-11e8-8541-fa944696e00d.png">

**Comment by cyberhobo** [comment]
I've [updated the docs](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Getting-Started/_compare/b8b78d55e2537a86cb49b7927f779c94a09b4bcf...8b11d44f4360639a0c2b43d9896f7c866a457cab).

**Comment by jerclarke** [comment]
Thanks that's a good start. In terms of these different types of embeds, could you say which category the different uses of GM fall into? 

i.e. What do the post editor map, frontend map for single post location, frontend map showing multiple points etc. qualify as in terms of these free and paid types of embed?

<img width="388" alt="screen shot 2018-11-16 at 15 12 37 pm" src="https://user-images.githubusercontent.com/139995/48647663-3f490280-e9b2-11e8-8c06-09ffc10281e8.png">

I'm guessing that for a lot of sites with limited traffic, the $200 is often enough to keep it free. 

Am I right that disabling street view could serve to keep the cost down?

**Comment by cyberhobo** [comment]
I linked to the [Dynamic Maps](https://developers.google.com/maps/billing/understanding-cost-of-use#dynamic-maps) category because Javascript API usage falls under that category by my reading, with or without Street View. Geo Mashup does have a static [option](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Tag-Reference#map-options) that should be able to generate a cheaper static map in some cases.
