### ISSUE TITLE
Geocode Custom field not working with multiple fields

### ISSUE THREAD

**Issue by smadds** [cyberhobo/wordpress-geo-mashup#835]
Is there a problem with the Geocode Custom Field part of the code if multiple fields are given?

If I just put `my_postcode` into the field, it works but if I put `my_streetaddress, my_town, my_postcode` (which would give me better accuracy) it fails and does not enter a geolocation.

Doesn't seem to matter if I leave out the spaces (`my_streetaddress,my_town,my_postcode`)

Any ideas?

**Comment by cyberhobo** [comment]
There could be a bug, I don't currently have an automated test for multiples. Do any of your posts where it failed have a geocoding_error custom field added with more information?

**Comment by cyberhobo** [comment]
Added a test, but found no problems.
