### ISSUE TITLE
Update leaflet provider

### ISSUE THREAD

**Issue by Birtakimseyler** [cyberhobo/wordpress-geo-mashup#843]
Hello, I would like to update leaflet.js library from 0.7.7 to 1.0.0 or more. (Actual version is 1.5.1) It seems leaflet have a lot of [fixes and improvements](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) until the last version.

When I change leaflet.js and css versions from the [render-map.php ](https://github.com/cyberhobo/wordpress-geo-mashup/blob/develop/render-map.php#L298), it seems working well, except the marker colors. Markers became default marker icon of the leaflet library. Except this issue, I didn't see any other problem. It should be about taxonomy but unfortunately my ability is not enought to find the exact related codes. 

Is it a big changes, or is it something I can be solved with your help?
Thank you.

**Comment by cyberhobo** [comment]
I'm pretty sure I've tried this and run into trouble implementing some features, but I'll use this to remind me to take another look when I can.
