### ISSUE TITLE
google maps search bar

### ISSUE THREAD

**Issue by Photogad** [cyberhobo/wordpress-geo-mashup#854]
Is there a way to enable google maps search bar to center the map on a location (so user can see near them easier)?

I tried with
`[geo_mashup_map add_google_bar="true" add_map_control="true" add_overview_control="true"]`

but it's not working
https://earththroughthelens.com/map/

**Comment by cyberhobo** [comment]
Google removed that control from their API and I forgot to take it out of the documentation, sorry for that.

**Comment by Photogad** [comment]
Is this it or a different api?

https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

**Comment by cyberhobo** [comment]
That example uses the additional Places library, which Geo Mashup doesn't currently include. The old Google bar control was included in the core API before it was removed.
