### ISSUE TITLE
Search Using Zip code Wordpress 

### ISSUE THREAD

**Issue by rezwan1-qaderi** [cyberhobo/wordpress-geo-mashup#869]
I am trying to find a plugin that can search using zip code of area, like user put the zip code of area and search, in result users gets the available companies in that area. 

I am really stuck on this, I cannot figure out a way to do this. 
please anyone can help me with this.

**Comment by cyberhobo** [comment]
I think you're looking for the [search widget](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Feature-Usage#geo-mashup-search-widget).
