### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by matteolcd** [cyberhobo/wordpress-geo-mashup#871]
Hi! 
In general map, when i click on pointer the info window doesen't open and there's this error on console:

`https://mysite.com?geo_mashup_content=geo-query&map_name=gm-map-1&object_name=post&object_ids=32747 (403)`

Can someone helpme?
Tnx

**Comment by cyberhobo** [comment]
The [403 Forbidden](https://en.wikipedia.org/wiki/HTTP_403) response indicates that something on the server is configured to refuse the request. This could be another plugin or security software on the server. The next place to look for clues would be in the web server PHP error log.
