### ISSUE TITLE
As of jQuery 1.9 global Ajax events are only triggered on document element

### ISSUE THREAD

**Issue by peter-nl** [cyberhobo/wordpress-geo-mashup#872]
Thanks for this great plugin!!

In latest GeoMashup v1.13.3 line 587 in https://github.com/cyberhobo/wordpress-geo-mashup/blob/master/js/location-editor.js

`$ajax_message.ajaxError( function( event, request, settings ) {`

with WP 5.5(.1) causes an issue; ajaxError should be attached to the document.

Anyone who's looking for a simple work-around can temporarily use Automattic's https://nl.wordpress.org/plugins/enable-jquery-migrate-helper/.

Kind regards,
Peter

**Comment by cyberhobo** [comment]
Thanks for the report! Hopefully this is an easy fix.
