### ISSUE TITLE
Panning too fast in OpenLayers mode

### ISSUE THREAD

**Issue by kosik86** [cyberhobo/wordpress-geo-mashup#873]
I noticed an issue when using OpenLayers. When panning the map (on touch screens or drag&drop on desktop) the map is moving too fast. 

Has anyone seen similar problems? I'm still looking into this but there isn't any obvious reason why this is happening. 
The same issue doesn't happen when using leafletjs.

**Comment by cyberhobo** [comment]
I see this too, I'll take a look at it for the next release.
