### ISSUE TITLE
MAP with sumary or condensed display of pins

### ISSUE THREAD

**Issue by oe3seu** [cyberhobo/wordpress-geo-mashup#880]
how can I parameter a map to show many location in condensed view (eg. (153 Norway, 80 Sweden ...)?

see example attached

![mapexample](https://user-images.githubusercontent.com/74486979/99180123-df61cf80-2723-11eb-839f-e4ea1858ccad.jpg)

**Comment by cyberhobo** [comment]
The [wordpress.org community support forum](https://wordpress.org/support/plugin/geo-mashup/) is a better place for support questions, I use GitHub primarily for tracking bugs and new features. The feature you're looking for is [clustering](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Feature-Usage#clustering).
