### ISSUE TITLE
Changing CLUSTER icon color?

### ISSUE THREAD

**Issue by oe3seu** [cyberhobo/wordpress-geo-mashup#883]
Clusters are represented by a partially transparent red circle icon.

How could I change the circle icon color?

**Comment by cyberhobo** [comment]
The [wordpress.org community support forum](https://wordpress.org/support/plugin/geo-mashup/) is a better place for support questions, I use GitHub primarily for tracking bugs and new features.

There isn't an existing feature for this, but it should be possible using the [javascript API](https://github.com/cyberhobo/wordpress-geo-mashup/wiki/Javascript-API).
