### ISSUE TITLE
Vulnerabilities found in 1.13.5

### ISSUE THREAD

**Issue by pau1phi11ips** [cyberhobo/wordpress-geo-mashup#896]
WordPress toolkit highlighted these vulnerabilities in 1.13.5 (current latest version)

- https://patchstack.com/database/vulnerability/geo-mashup/wordpress-geo-mashup-plugin-1135-toggle-the-debug-mode-via-cross-site-request-forgery-csrf-vulnerability
- https://patchstack.com/database/vulnerability/geo-mashup/wordpress-geo-mashup-plugin-1135-sensitive-information-disclosure-vulnerability

**Comment by cyberhobo** [comment]
Fixed in 1.13.6 by 9dbba1a549e5c8fe6931b6ea0959fc117e115798.

**Comment by pau1phi11ips** [comment]
Thanks for the prompt action!
