### ISSUE TITLE
Geo Mashup and PHP8

### ISSUE THREAD

**Issue by terrypro68** [cyberhobo/wordpress-geo-mashup#899]
Geo Mashup doesn't seem to be working well with PHP8. 
Layouts of Search From and Search Result looks broken.
Are there any plans to upgrade Geo Mashup to PHP8?
Thank you!

**Comment by cyberhobo** [comment]
Thanks for the issue, I do intend to try for PHP8 support.

**Comment by cyberhobo** [comment]
I've done some testing with PHP 8.0.18 and haven't found any issues, I'll try PHP 8.1 next.

**Comment by terrypro68** [comment]
Thank you for the reply. 
It seems like **Geo Mashup Custom** is not hooking up.
Do you think you could test Geo Mashup Custom as well? 
Thank you!

**Comment by terrypro68** [comment]
Thank you! The problem was in Custom Geo Mashup.

**Comment by cyberhobo** [comment]
That makes sense. I should update the custom plugin for new users, I do have a repository for it: https://github.com/cyberhobo/geo-mashup-custom/issues. If you were able to fix the problem details might help me.

**Comment by terrypro68** [comment]
ok!
