### ISSUE TITLE
No option for GoogleV2, so no kml? 

### ISSUE THREAD

**Issue by buddhabackpacker** [cyberhobo/wordpress-geo-mashup#921]
I really like this plugin - easy to use and understand.  I'm just checking it out now and I saw documentation about using KML files in V2 of Google maps, but there is no option to select V2.  Has KML gone away completely from this plugin?
Thanks!

**Comment by cyberhobo** [comment]
The display of KML files works with all the current providers. The problem I hit with this feature is that WordPress started disallowing uploads of KML files, and I never found a reliable method to lift that restriction.

**Comment by buddhabackpacker** [comment]
You can add mime types to the plugin functions file using the filter 'upload_mimes’.  Have you tried that?  I haven’t been writing much code for Wordpress in a couple years so they might have changed something, but I’ve used this for plugins before.  Thanks for answering so quickly.

**Comment by cyberhobo** [comment]
Yes, that code is still there (https://github.com/cyberhobo/wordpress-geo-mashup/blob/a8c04b426dcf4b38d974c9683b3997d0672894ee/geo-mashup-ui-managers.php#L588) but I think it stopped working with the Gutenberg editor and I wasn't able to revive it.
