### ISSUE TITLE
Styling with custom STD does not work with me

### ISSUE THREAD

**Issue by stgoldmann** [cyberhobo/wordpress-geo-mashup#925]
Hi,

I had styling on my maps (markers, landmass, etc), but somehow it disappeared during the last months. Now I wanted to redo it again, but nothing seems to work. 
So I need to ask: Is the Geo Mashup Custom STD still working at all?
Example to be seen here: https://www.myhighlands.de/regionen/

Kind regards

Stephan

**Comment by cyberhobo** [comment]
It's possible that the Geo Mashup Custom plugin needs updates to work with current versions of PHP, I'll take a look. Thanks for letting me know!

**Comment by stgoldmann** [comment]
Cool, would be nice, if it works again. BTW: Just paid for the plugin, it really needs to go on. But the support Mail ist not working anymore.

**Comment by cyberhobo** [comment]
This version fixes the only error I was getting with PHP 8.3. If you copy just the `geo-mashup-custom.php` over yours does it work? 

https://github.com/cyberhobo/geo-mashup-custom/blob/textdomain-error/geo-mashup-custom.php

**Comment by stgoldmann** [comment]
I needed to use it as "geo-mashup-custom-std.php". But indeed, that seems to do the trick. Thank you. I will have an eye on it, if I see somethnig buggy.

**Comment by cyberhobo** [comment]
I've released that as a the current version of the Geo Mashup Custom plugin and updated the docs to reference it. Thank you.
